export type ProjectVisibility = "public" | "private" | "private-or-redacted";

export type ProjectSlug =
  | "jogyo-clock"
  | "jy-workation"
  | "karj"
  | "karj-admin"
  | "ta-ticket"
  | "coreprint"
  | "scurt"
  | "qa-image";

export type ProjectStatus =
  | "Live"
  | "Built"
  | "Prototype"
  | "In Progress"
  | "Private Client Work"
  | "Archived";

export type Project = {
  title: string;
  slug: ProjectSlug;
  description: string;
  longDescription?: string;
  tags: string[];
  status: ProjectStatus;
  visibility: ProjectVisibility;
  githubUrl?: string;
  liveUrl?: string;
  featured?: boolean;
};

export const projects: Project[] = [
  {
    title: "Jogyo Clock",
    slug: "jogyo-clock",
    description:
      "An exam proctoring clock web app for classroom projection, built around current time, remaining time, announcements, fullscreen mode, presets, themes, and exam-flow controls.",
    longDescription:
      "Designed for real supervision contexts, Jogyo Clock works locally without login and can use Firebase for Google sign-in, cloud presets, room entries, and public read-only share links.",
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "Firebase", "Productivity"],
    status: "Live",
    visibility: "public",
    githubUrl: "https://github.com/hajun-myoung/jogyo",
    featured: true,
  },
  {
    title: "jy-workation",
    slug: "jy-workation",
    description:
      "A retreat and track-management platform that turns proposals, schedules, and participant flows into a cleaner product experience for church operations.",
    tags: ["React", "Firebase", "Firestore", "Public Forms", "Church Tech"],
    status: "Built",
    visibility: "private",
    featured: true,
  },
  {
    title: "karj",
    slug: "karj",
    description:
      "A private LMS enhancement project built around Campaignus, adding course progress tracking and automated certificate generation through Firebase Functions.",
    tags: ["Firebase Functions", "LMS", "Automation", "Certificate", "Campaignus"],
    status: "Private Client Work",
    visibility: "private",
    featured: true,
  },
  {
    title: "karj-admin",
    slug: "karj-admin",
    description:
      "A private admin dashboard for viewing LMS certificate records generated by KARJ, built with React and MUI for clean administrator workflows.",
    tags: ["React", "MUI", "Admin Dashboard", "Data Table", "Firebase"],
    status: "Private Client Work",
    visibility: "private",
    featured: true,
  },
  {
    title: "TA Ticket",
    slug: "ta-ticket",
    description:
      "A controlled ticketing and seat-reservation service for a 185-seat event/classroom-style environment, with realtime seat locking, reservation windows, and barcode ticket views.",
    longDescription:
      "Built with React, TypeScript, Vite, MUI, and Firebase Realtime Database for small-scale controlled ticketing where seat state needs to be visible and coordinated.",
    tags: ["React", "TypeScript", "Vite", "Firebase", "Ticketing"],
    status: "Built",
    visibility: "public",
    githubUrl: "https://github.com/hajun-myoung/ta-ticket",
    featured: true,
  },
  {
    title: "CorePrint",
    slug: "coreprint",
    description:
      "A print workflow product concept focused on operational clarity, production requests, and reliable handoff between teams.",
    tags: ["Next.js", "Tailwind CSS", "Product Design", "Workflow"],
    status: "Built",
    visibility: "private-or-redacted",
    featured: true,
  },
  {
    title: "sCURT",
    slug: "scurt",
    description:
      "An image-processing demo that connects a clean frontend with a FastAPI backend, OpenCV processing, and research-facing output flows.",
    tags: ["Next.js", "FastAPI", "OpenCV", "Python"],
    status: "Prototype",
    visibility: "public",
    featured: true,
  },
  {
    title: "QA-image",
    slug: "qa-image",
    description:
      "A Firebase-powered image and PDF review tool with viewer workflows, storage handling, and practical admin configuration surfaces.",
    tags: ["React", "Firebase", "Storage", "PDF Viewer"],
    status: "Built",
    visibility: "private-or-redacted",
    featured: true,
  },
];
